# Generated by Django 4.2.11 on 2024-04-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SVG2', '0004_alter_household_construction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('reservation_date', models.DateField()),
                ('reservation_time_start', models.TimeField()),
                ('reservation_time_end', models.TimeField()),
                ('amenities', models.CharField(choices=[('Court', 'Court'), ('Chairs & Tables', 'Chairs & Tables'), ('Event Hall', 'Event Hall')], max_length=100)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('denied', 'Denied')], default='pending', max_length=10)),
            ],
        ),
    ]
