# Generated by Django 4.2.11 on 2024-04-10 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SVG2', '0008_billing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billing',
            options={'ordering': ['-billing_month']},
        ),
        migrations.AlterField(
            model_name='billing',
            name='billing_month',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='billing',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='SVG2.household'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='unpaid', max_length=7),
        ),
        migrations.AlterUniqueTogether(
            name='billing',
            unique_together={('household', 'billing_month')},
        ),
    ]
