# Generated by Django 4.2.11 on 2024-04-10 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SVG2', '0010_remove_reservation_address_remove_reservation_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='submitter',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='household',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='SVG2.household'),
            preserve_default=False,
        ),
    ]
