# Generated by Django 4.2.11 on 2024-04-10 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SVG2', '0014_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Newsfeed',
        ),
    ]
