# Generated by Django 4.2.11 on 2024-04-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SVG2', '0016_alter_reservation_status_alter_resident_birthdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
