# Generated by Django 4.2.11 on 2024-04-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SVG2', '0017_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='newsfeed',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='C:/HOA_MIS/media/news_notices'),
        ),
    ]
