# Generated by Django 4.2.11 on 2024-04-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SVG2', '0020_remove_officer_birthdate_remove_officer_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='C:/HOA_MIS/media/profile_pics/'),
        ),
    ]
