# Generated by Django 4.2.11 on 2024-04-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SVG2', '0021_alter_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
