# Generated by Django 4.2.11 on 2024-04-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SVG2', '0022_contactsender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='officer_position',
            field=models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('Auditor', 'Auditor'), ('P.R.O.', 'P.R.O.'), ('Grievance & Adjudication', 'Grievance & Adjudication'), ('Business & Finance', 'Business & Finance'), ('Peace & Order', 'Peace & Order'), ('Sports Committee', 'Sports Committee'), ('Seniors Affair', 'Seniors Affair')], max_length=50),
        ),
    ]
