# Generated by Django 4.2.11 on 2024-10-01 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SVG2', '0025_grievanceappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievanceappointment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='C:/HOA_MIS/media/news_notices'),
        ),
        migrations.AlterField(
            model_name='grievanceappointment',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grievance_appointments', to='SVG2.household'),
        ),
    ]
