# Generated by Django 4.2.11 on 2024-10-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SVG2', '0027_alter_reservation_status_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
    ]
