# Generated by Django 4.2.11 on 2024-10-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SVG2', '0028_alter_resident_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Submitted', max_length=20),
        ),
    ]
