# Generated by Django 4.2.11 on 2024-10-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SVG2', '0029_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievanceappointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Denied', 'Denied'), ('Canceled', 'Canceled')], default='Pending', max_length=10),
        ),
    ]
