# Generated by Django 4.2.11 on 2024-11-13 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SVG2', '0031_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='read',
        ),
    ]
