# Generated by Django 4.2.11 on 2024-11-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SVG2', '0032_remove_notification_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
