# Generated by Django 4.2.11 on 2024-12-08 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SVG2', '0035_grievanceappointment_appointment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status_changed_by_officer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='billing',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='300', max_digits=10),
        ),
        migrations.AlterField(
            model_name='billing',
            name='status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Overdue', 'Overdue')], default='Unpaid', max_length=7),
        ),
        migrations.AlterField(
            model_name='grievanceappointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Denied', 'Denied'), ('Canceled', 'Canceled'), ('Rescheduled', 'Rescheduled')], default='Pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='household',
            name='owner_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='household', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='amenities',
            field=models.CharField(choices=[('Court', 'Court'), ('Chairs & Tables', 'Chairs & Tables'), ('Event Hall', 'Event Hall')], default='Court', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(choices=[('Maintenance Request', 'Maintenance Request'), ('Incident Report', 'Incident Report')], default='Maintenance Request', max_length=20),
        ),
    ]
