# Generated by Django 4.2.11 on 2024-12-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SVG2', '0036_reservation_status_changed_by_officer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievanceappointment',
            name='status_changed_by_officer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='status_changed_by_officer',
            field=models.BooleanField(default=False),
        ),
    ]
