# Generated by Django 4.2.11 on 2024-12-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SVG2', '0038_household_details_changed_by_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='details_changed_by_officer',
            field=models.BooleanField(default=False),
        ),
    ]
