# Generated by Django 4.2.11 on 2024-12-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SVG2', '0040_remove_notification_household_notification_recipient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='billing',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='SVG2_notifi_created_cb8278_idx'),
        ),
    ]
