# Generated by Django 4.2.11 on 2024-12-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SVG2', '0042_alter_billing_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievanceappointment',
            name='appointment_type',
            field=models.CharField(choices=[('Certification', 'Certification'), ('Grievance', 'Grievance'), ('Others', 'Others')], default='Certification', max_length=20),
        ),
    ]
